.. Shared image references

.. |img-user-menu| image:: /images/user-menu.svg
   :width: 80%

.. |img-user-add| image:: /images/user-add.svg
   :width: 80%

.. |img-user-dialog| image:: /images/user-dialog.svg
   :width: 80%

.. |img-user-click-edit| image:: /images/user-click-edit.svg
   :width: 80%

.. |img-user-perms| image:: /images/user-perms.svg
   :width: 80%

.. |img-user-add-access| image:: /images/user-add-access.svg
   :width: 80%

.. |img-user-done| image:: /images/user-done.svg
   :width: 80%

.. |img-connection| image:: /images/connection.svg
   :width: 100%

.. |img-person-graph| image:: /images/person-graph.png
   :width: 100%

.. |img-hippieoil| image:: /images/hippieoil.png
   :width: 100%

.. |img-library-graph| image:: /images/library-graph.png
   :width: 100%

.. |img-event-store-source| image:: /images/event-store-source.png
   :width: 100%