.. Common substitutions, included in rst_epilog (i.e. available in all documents)

.. Class references (including the whole package breaks source readability, 
   so it is cleaner to use a substitution)

.. |RepositoryConnection| replace:: :class:`~franz.openrdf.repository.repositoryconnection.RepositoryConnection`
.. |Repository| replace:: :class:`~franz.openrdf.repository.repository.Repository`
.. |RepositoryResult| replace:: :class:`~franz.openrdf.repository.repositoryresult.RepositoryResult`
.. |TupleQueryResult| replace:: :class:`~franz.openrdf.query.queryresult.TupleQueryResult`
.. |RDFFormat| replace:: :class:`franz.openrdf.rio.rdfformat.RDFFormat`
.. |Query| replace:: :class:`~franz.openrdf.query.query.Query`
.. |TupleQuery| replace:: :class:`~franz.openrdf.query.query.TupleQuery`
.. |GraphQuery| replace:: :class:`~franz.openrdf.query.query.GraphQuery`
.. |BooleanQuery| replace:: :class:`~franz.openrdf.query.query.BooleanQuery`
.. |UpdateQuery| replace:: :class:`~franz.openrdf.query.query.UpdateQuery`
.. |Statement| replace:: :class:`~franz.openrdf.model.Statement`
