from __future__ import unicode_literals
import os.path
import pkg_resources
import subprocess

# Determine version number

__version__ = None

# Try asking setuptools first.
try:
    __version__ = pkg_resources.require('agraph-python')[0].version
except:   # A ton of different errors can be thrown by distutils...
    pass

# Root directory of the distribution or source checkout.
root = os.path.normpath(os.path.join(
    os.path.dirname(os.path.realpath(__file__)), '../../'))

# Try reading it from a VERSION file otherwise.
# It is generated by Nakefile and included in the distribution.
if __version__ is None:
    path = os.path.join(root, 'VERSION')
    try:
        with open(path, 'rb') as version_file:
            __version__ = version_file.read().strip()
    except IOError:
        pass

# Otherwise assume we're inside agraph sources
if __version__ is None:
    agraph_root = os.path.normpath(os.path.join(root, '../agraph/lisp/'))
    __version__ = subprocess.Popen(
        os.path.normpath(os.path.join(agraph_root, 
                                      'build-tools/agversion.sh')), 
        stdout=subprocess.PIPE).communicate()[0]
