.. Shared image references

.. |img-user-menu| image:: /images/user-menu.svg
   :width: 80%

.. |img-user-add| image:: /images/user-add.svg
   :width: 80%

.. |img-user-dialog| image:: /images/user-dialog.svg
   :width: 80%

.. |img-user-click-edit| image:: /images/user-click-edit.svg
   :width: 80%

.. |img-user-perms| image:: /images/user-perms.svg
   :width: 80%

.. |img-user-add-access| image:: /images/user-add-access.svg
   :width: 80%

.. |img-user-done| image:: /images/user-done.svg
   :width: 80%

.. |img-connection| image:: /images/connection.svg
   :width: 100%